#!/usr/bin/env bash
unset ENSTORE_OUT
unset ENSTORE_MAIL
unset QPID_DIR
unset GADFLY_GRAMMAR
unset CVSROOT
unset PYTHONUNBUFFERED
unset PYTHON_DIR
unset ENSTORE_HOME
unset ENSSH
unset ENSTORE_SFA_POLICY
unset ENSCP
unset ENSTORE_CONFIG_HOST
unset ENSTORE_GIT
export PATH=/opt/miniconda3/condabin:/usr/krb5/sbin:/usr/krb5/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
unset ENSTORE_CONFIG_DIR
unset ENSTORE_CONF_GIT
unset PYTHONINC
unset ENSTORE_CONFIG_PORT
unset ENSTORE_CONFIG_FILE
unset SWIG_LIB
unset FTT_DIR
unset PYTHONPATH
unset PYTHONLIB
unset FARMLETS_DIR
unset ENSTORE_DIR
unset ENSTORE_GANG
unset SWIG_DIR
